"""initial portable schema

Revision ID: 20260715_0001
Revises:
Create Date: 2026-07-15 16:59:31.601006
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260715_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=30), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["org_units.id"], name=op.f("fk_org_units_parent_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_units")),
    )
    with op.batch_alter_table("org_units", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_org_units_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_org_units_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "persons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identifier_encrypted", sa.String(length=512), nullable=True),
        sa.Column("identifier_hash", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("rank", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("status_reason", sa.String(length=100), nullable=True),
        sa.Column("status_effective_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
    )
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_persons_identifier_hash"), ["identifier_hash"], unique=True
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name_normalized", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name_normalized", name=op.f("uq_tags_name_normalized")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_person_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("subject_type", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("metadata_text", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_person_id"], ["persons.id"], name=op.f("fk_audit_logs_actor_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_actor_person_id"), ["actor_person_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_event_type"), ["event_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_subject_id"), ["subject_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_subject_type"), ["subject_type"], unique=False
        )

    op.create_table(
        "exam_papers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("question_selection_mode", sa.String(length=30), nullable=False),
        sa.Column("pool_criteria_text", sa.Text(), nullable=True),
        sa.Column("variant_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["persons.id"], name=op.f("fk_exam_papers_created_by_persons")
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_units.id"], name=op.f("fk_exam_papers_org_unit_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_papers")),
    )
    with op.batch_alter_table("exam_papers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_papers_org_unit_id"), ["org_unit_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exam_papers_status"), ["status"], unique=False)

    op.create_table(
        "person_unit_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_units.id"],
            name=op.f("fk_person_unit_assignments_org_unit_id_org_units"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_person_unit_assignments_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_unit_assignments")),
    )
    with op.batch_alter_table("person_unit_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_person_unit_assignments_effective_to"), ["effective_to"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_person_unit_assignments_org_unit_id"), ["org_unit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_person_unit_assignments_person_id"), ["person_id"], unique=False
        )

    op.create_table(
        "personnel_import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_checksum", sa.String(length=64), nullable=False),
        sa.Column("import_mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("added_count", sa.Integer(), nullable=False),
        sa.Column("changed_count", sa.Integer(), nullable=False),
        sa.Column("moved_count", sa.Integer(), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("error_summary_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["persons.id"],
            name=op.f("fk_personnel_import_batches_uploaded_by_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personnel_import_batches")),
    )
    with op.batch_alter_table("personnel_import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_personnel_import_batches_file_checksum"), ["file_checksum"], unique=True
        )

    op.create_table(
        "question_banks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_org_unit_id", sa.Uuid(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["persons.id"], name=op.f("fk_question_banks_created_by_persons")
        ),
        sa.ForeignKeyConstraint(
            ["owner_org_unit_id"],
            ["org_units.id"],
            name=op.f("fk_question_banks_owner_org_unit_id_org_units"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_banks")),
    )
    with op.batch_alter_table("question_banks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_banks_owner_org_unit_id"), ["owner_org_unit_id"], unique=False
        )

    op.create_table(
        "user_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("username_normalized", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_user_accounts_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_accounts")),
        sa.UniqueConstraint("person_id", name=op.f("uq_user_accounts_person_id")),
    )
    with op.batch_alter_table("user_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_accounts_username_normalized"), ["username_normalized"], unique=True
        )

    op.create_table(
        "exam_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_paper_id", sa.Uuid(), nullable=False),
        sa.Column("variant_label", sa.String(length=20), nullable=False),
        sa.Column("generation_seed_reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_paper_id"],
            ["exam_papers.id"],
            name=op.f("fk_exam_variants_exam_paper_id_exam_papers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_variants")),
        sa.UniqueConstraint("exam_paper_id", "variant_label", name="uq_paper_variant_label"),
    )
    with op.batch_alter_table("exam_variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_variants_exam_paper_id"), ["exam_paper_id"], unique=False
        )

    op.create_table(
        "exam_windows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_paper_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("window_open_at", sa.DateTime(), nullable=True),
        sa.Column("window_close_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["persons.id"], name=op.f("fk_exam_windows_created_by_persons")
        ),
        sa.ForeignKeyConstraint(
            ["exam_paper_id"],
            ["exam_papers.id"],
            name=op.f("fk_exam_windows_exam_paper_id_exam_papers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_windows")),
    )
    with op.batch_alter_table("exam_windows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_windows_exam_paper_id"), ["exam_paper_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exam_windows_status"), ["status"], unique=False)

    op.create_table(
        "personnel_import_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data_text", sa.Text(), nullable=False),
        sa.Column("normalized_identifier_hash", sa.String(length=64), nullable=True),
        sa.Column("validation_status", sa.String(length=30), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["personnel_import_batches.id"],
            name=op.f("fk_personnel_import_rows_batch_id_personnel_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personnel_import_rows")),
    )
    with op.batch_alter_table("personnel_import_rows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_personnel_import_rows_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_personnel_import_rows_normalized_identifier_hash"),
            ["normalized_identifier_hash"],
            unique=False,
        )

    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.String(length=30), nullable=True),
        sa.Column("default_score_weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["question_banks.id"], name=op.f("fk_questions_bank_id_question_banks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_bank_id"), ["bank_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_difficulty"), ["difficulty"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_status"), ["status"], unique=False)

    op.create_table(
        "exam_paper_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_paper_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("base_order_index", sa.Integer(), nullable=False),
        sa.Column("score_weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_paper_id"],
            ["exam_papers.id"],
            name=op.f("fk_exam_paper_questions_exam_paper_id_exam_papers"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_exam_paper_questions_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_paper_questions")),
        sa.UniqueConstraint("exam_paper_id", "question_id", name="uq_paper_question"),
    )
    with op.batch_alter_table("exam_paper_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_paper_questions_exam_paper_id"), ["exam_paper_id"], unique=False
        )

    op.create_table(
        "exam_paper_selected_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_paper_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("score_weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_paper_id"],
            ["exam_papers.id"],
            name=op.f("fk_exam_paper_selected_questions_exam_paper_id_exam_papers"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_exam_paper_selected_questions_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_paper_selected_questions")),
        sa.UniqueConstraint("exam_paper_id", "question_id", name="uq_selected_paper_question"),
    )
    with op.batch_alter_table("exam_paper_selected_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_paper_selected_questions_exam_paper_id"),
            ["exam_paper_id"],
            unique=False,
        )

    op.create_table(
        "exam_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("exam_window_id", sa.Uuid(), nullable=False),
        sa.Column("exam_variant_id", sa.Uuid(), nullable=False),
        sa.Column("examinee_snapshot_text", sa.Text(), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_variant_id"],
            ["exam_variants.id"],
            name=op.f("fk_exam_sessions_exam_variant_id_exam_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_window_id"],
            ["exam_windows.id"],
            name=op.f("fk_exam_sessions_exam_window_id_exam_windows"),
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_units.id"], name=op.f("fk_exam_sessions_org_unit_id_org_units")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_exam_sessions_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_sessions")),
        sa.UniqueConstraint("person_id", "exam_window_id", name="uq_person_exam_window"),
    )
    with op.batch_alter_table("exam_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_sessions_exam_window_id"), ["exam_window_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exam_sessions_org_unit_id"), ["org_unit_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exam_sessions_person_id"), ["person_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_exam_sessions_status"), ["status"], unique=False)

    op.create_table(
        "exam_window_scopes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_window_id", sa.Uuid(), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_window_id"],
            ["exam_windows.id"],
            name=op.f("fk_exam_window_scopes_exam_window_id_exam_windows"),
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_units.id"],
            name=op.f("fk_exam_window_scopes_org_unit_id_org_units"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_window_scopes")),
        sa.UniqueConstraint("exam_window_id", "org_unit_id", name="uq_window_org_scope"),
    )
    with op.batch_alter_table("exam_window_scopes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_window_scopes_exam_window_id"), ["exam_window_id"], unique=False
        )

    op.create_table(
        "question_choices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("base_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_choices_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_choices")),
        sa.UniqueConstraint("question_id", "base_order", name="uq_question_choice_base_order"),
    )
    with op.batch_alter_table("question_choices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_choices_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "question_tags",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_question_tags_question_id_questions")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_question_tags_tag_id_tags")),
        sa.PrimaryKeyConstraint("question_id", "tag_id", name=op.f("pk_question_tags")),
    )
    op.create_table(
        "question_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("content_snapshot", sa.Text(), nullable=False),
        sa.Column("choices_snapshot_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_versions_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_versions")),
    )
    with op.batch_alter_table("question_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_versions_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "exam_variant_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_variant_id", sa.Uuid(), nullable=False),
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("choice_display_order_text", sa.Text(), nullable=False),
        sa.Column("score_weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_variant_id"],
            ["exam_variants.id"],
            name=op.f("fk_exam_variant_questions_exam_variant_id_exam_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_exam_variant_questions_question_version_id_question_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_variant_questions")),
        sa.UniqueConstraint(
            "exam_variant_id", "question_version_id", name="uq_variant_question_version"
        ),
    )
    with op.batch_alter_table("exam_variant_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_variant_questions_exam_variant_id"),
            ["exam_variant_id"],
            unique=False,
        )

    op.create_table(
        "exam_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_session_id", sa.Uuid(), nullable=False),
        sa.Column("exam_variant_question_id", sa.Uuid(), nullable=False),
        sa.Column("selected_choice_id", sa.Uuid(), nullable=False),
        sa.Column("first_answered_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_correct_cache", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_session_id"],
            ["exam_sessions.id"],
            name=op.f("fk_exam_answers_exam_session_id_exam_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_variant_question_id"],
            ["exam_variant_questions.id"],
            name=op.f("fk_exam_answers_exam_variant_question_id_exam_variant_questions"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_choice_id"],
            ["question_choices.id"],
            name=op.f("fk_exam_answers_selected_choice_id_question_choices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_answers")),
        sa.UniqueConstraint(
            "exam_session_id", "exam_variant_question_id", name="uq_session_variant_question"
        ),
    )
    with op.batch_alter_table("exam_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_answers_exam_session_id"), ["exam_session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_answers_exam_session_id"))

    op.drop_table("exam_answers")
    with op.batch_alter_table("exam_variant_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_variant_questions_exam_variant_id"))

    op.drop_table("exam_variant_questions")
    with op.batch_alter_table("question_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_versions_question_id"))

    op.drop_table("question_versions")
    op.drop_table("question_tags")
    with op.batch_alter_table("question_choices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_choices_question_id"))

    op.drop_table("question_choices")
    with op.batch_alter_table("exam_window_scopes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_window_scopes_exam_window_id"))

    op.drop_table("exam_window_scopes")
    with op.batch_alter_table("exam_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_exam_sessions_person_id"))
        batch_op.drop_index(batch_op.f("ix_exam_sessions_org_unit_id"))
        batch_op.drop_index(batch_op.f("ix_exam_sessions_exam_window_id"))

    op.drop_table("exam_sessions")
    with op.batch_alter_table("exam_paper_selected_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_paper_selected_questions_exam_paper_id"))

    op.drop_table("exam_paper_selected_questions")
    with op.batch_alter_table("exam_paper_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_paper_questions_exam_paper_id"))

    op.drop_table("exam_paper_questions")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_status"))
        batch_op.drop_index(batch_op.f("ix_questions_difficulty"))
        batch_op.drop_index(batch_op.f("ix_questions_bank_id"))

    op.drop_table("questions")
    with op.batch_alter_table("personnel_import_rows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personnel_import_rows_normalized_identifier_hash"))
        batch_op.drop_index(batch_op.f("ix_personnel_import_rows_batch_id"))

    op.drop_table("personnel_import_rows")
    with op.batch_alter_table("exam_windows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_windows_status"))
        batch_op.drop_index(batch_op.f("ix_exam_windows_exam_paper_id"))

    op.drop_table("exam_windows")
    with op.batch_alter_table("exam_variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_variants_exam_paper_id"))

    op.drop_table("exam_variants")
    with op.batch_alter_table("user_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_accounts_username_normalized"))

    op.drop_table("user_accounts")
    with op.batch_alter_table("question_banks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_banks_owner_org_unit_id"))

    op.drop_table("question_banks")
    with op.batch_alter_table("personnel_import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personnel_import_batches_file_checksum"))

    op.drop_table("personnel_import_batches")
    with op.batch_alter_table("person_unit_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_person_unit_assignments_person_id"))
        batch_op.drop_index(batch_op.f("ix_person_unit_assignments_org_unit_id"))
        batch_op.drop_index(batch_op.f("ix_person_unit_assignments_effective_to"))

    op.drop_table("person_unit_assignments")
    with op.batch_alter_table("exam_papers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_papers_status"))
        batch_op.drop_index(batch_op.f("ix_exam_papers_org_unit_id"))

    op.drop_table("exam_papers")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_subject_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_subject_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_person_id"))

    op.drop_table("audit_logs")
    op.drop_table("tags")
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_persons_identifier_hash"))

    op.drop_table("persons")
    with op.batch_alter_table("org_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_units_parent_id"))
        batch_op.drop_index(batch_op.f("ix_org_units_code"))

    op.drop_table("org_units")
    # ### end Alembic commands ###
