<script setup lang="ts">
import { onMounted, ref } from "vue";
import AppAlert from "@/components/feedback/AppAlert.vue";
import PageContainer from "@/components/layout/PageContainer.vue";
import PageHeader from "@/components/layout/PageHeader.vue";
import { apiGet } from "@/api/client";
interface Report { employee_total: number; employee_active: number; employee_inactive: number; exam_in_progress: number; exam_submitted: number; average_score: number | null }
interface Creation { paper_id: string; title: string; subject_id: string | null; variant_count: number; session_total: number; submitted_total: number; in_progress_total: number; average_score: number | null }
const report = ref<Report | null>(null); const creations = ref<Creation[]>([]); const error = ref(""); const loading = ref(true);
onMounted(async () => { try { [report.value, creations.value] = await Promise.all([apiGet<Report>("/reports/summary"), apiGet<Creation[]>("/reports/exam-creations")]); } catch (e) { error.value = e instanceof Error ? e.message : "โหลดรายงานไม่สำเร็จ"; } finally { loading.value = false; } });
</script>
<template><PageContainer><PageHeader eyebrow="รายงาน" title="สถิติระบบและสถิติรายครั้ง" description="สถิติการสอบแยกตาม Exam Creation และไม่ปนกันระหว่างการสร้างคนละครั้ง" /><AppAlert v-if="loading"><span class="loading loading-spinner loading-sm"></span>กำลังโหลดรายงาน</AppAlert><AppAlert v-else-if="error" type="error">{{ error }}</AppAlert><template v-else><div v-if="report" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="item in [{label:'บุคลากรทั้งหมด',value:report.employee_total},{label:'กำลังทำข้อสอบ',value:report.exam_in_progress},{label:'ส่งข้อสอบแล้ว',value:report.exam_submitted},{label:'คะแนนเฉลี่ย',value:report.average_score ?? '-'}]" :key="item.label" class="stat rounded-2xl border border-base-300 bg-base-100 shadow-sm"><div class="stat-title">{{ item.label }}</div><div class="stat-value text-primary">{{ item.value }}</div></div></div><div class="mt-6 card border border-base-300 bg-base-100 shadow-sm"><div class="card-body"><h2 class="card-title">สถิติการสร้างข้อสอบแต่ละครั้ง</h2><div class="overflow-x-auto"><table class="table"><thead><tr><th>Exam Creation</th><th>ชุดข้อสอบ</th><th>ผู้เข้าสอบ</th><th>ส่งแล้ว</th><th>คะแนนเฉลี่ย</th></tr></thead><tbody><tr v-for="creation in creations" :key="creation.paper_id"><td>{{ creation.title }}</td><td>{{ creation.variant_count }}</td><td>{{ creation.session_total }}</td><td>{{ creation.submitted_total }}</td><td>{{ creation.average_score ?? '-' }}</td></tr><tr v-if="!creations.length"><td colspan="5" class="text-center text-base-content/60">ยังไม่มีข้อมูลการสอบ</td></tr></tbody></table></div></div></div></template></PageContainer></template>
